CREATE PLUGGABLE DATABASE <Nome PDB> ADMIN USER Admin IDENTIFIED BY "<Senha SYS e SYSTEM>" TEMPFILE REUSE;

ALTER PLUGGABLE DATABASE <Nome PDB> OPEN INSTANCES=ALL;

ALTER SESSION SET CONTAINER=<Nome PDB>;

COL WRL_PARAMETER FOR A45
SET LINESIZE 120
SELECT wrl_parameter, status, wallet_type FROM gv$encryption_wallet;

ADMINISTER KEY MANAGEMENT SET KEY USING TAG '<Nome PDB>' FORCE KEYSTORE IDENTIFIED BY <Senha SYS e SYSTEM> WITH BACKUP USING 'backup_<Nome PDB>';

COL WRL_PARAMETER FOR A45
SET LINESIZE 120
SELECT wrl_parameter, status, wallet_type FROM gv$encryption_wallet;

ALTER SYSTEM SET DB_PERFORMANCE_PROFILE='SILVER' SCOPE=SPFILE;
