-- Altera o PDB de "READ WRITE" para "MOUNTED"
ALTER PLUGGABLE DATABASE <Nome PDB> CLOSE INSTANCES=ALL;

ALTER PLUGGABLE DATABASE <Nome PDB>CLOSE IMMEDIATE INSTANCES=ALL;

-- Drop o PDB
DROP PLUGGABLE DATABASE <NomePdb> INCLUDING DATAFILES;
